name: artifact

on: [push]

env:
  ARTIFACT_NAME: myartifact

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Upload artifact for linux
      uses: actions/upload-artifact@v4
      with:
        name: env.ARTIFACT_NAME
        path: .

    - name: Python Syntax Checker
  # You may pin to the exact commit or the version.
  # uses: cclauss/Find-Python-syntax-errors-action@90f67be9fb626b675a3971b1d08ab29851cb721f
      uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
          
